# Generated by Django 4.2.11 on 2024-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default_profile_pic.jpg",
                upload_to="profile_pics/",
            ),
        ),
    ]
