# Generated by Django 4.2.11 on 2024-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_loginhistory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginHistory",
            new_name="LoginHistoryModel",
        ),
    ]
