# Generated by Django 4.2.11 on 2024-05-01 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_loginhistory_loginhistorymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JsonFileModel",
        ),
    ]
