# Generated by Django 4.2.11 on 2024-05-01 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_delete_jsonfilemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginhistorymodel",
            name="logout_time",
        ),
    ]
